import { NextPage } from "next";
import Page from "../components/Page";
import NormalScene from "../components/NormalScene/NormalScene";

const Index: NextPage = () => {
  return (
    <Page title="san" description="Generated by Create Next Stack.">
      <NormalScene />
    </Page>
  );
};

export default Index;
